---
# tasks file for docker_tools
- name: Ensure DOCKER, PYTHON and MC packages are present
  apt:
    name: [ 'docker.io' , 'python3-pip', 'mc' ]
    state: present
    update_cache: yes

- name: Ensure DOCKER-PY python SDK for DOCKER is present
  pip:
    name: docker-py
    state: present