---
# tasks file for containerserver
- name: Ensure container is present on host and running
  docker_container:
      name: '{{ docker_container }}'
      image: '{{ docker_image }}'
      state: started
      ports:
        - "80:8080"